spring:
    application:
          name: spring-boot-config-server

# Eureka client configurations
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
